### ISSUE TITLE
conda-forge to autodeploy after PyPI package updates

### ISSUE THREAD

**Issue by pz-max** [pypsa-meets-earth/earth-osm#11]
Detailed description can be found [here](https://levelup.gitconnected.com/publishing-your-python-package-on-conda-and-conda-forge-309a405740cf).  Below I am posting the content.

## conda-forge

Conda-forge is by far my favorite place to publish python packages. Before a package can be published on conda-forge it must go through a brief review process, and all of its dependencies must be already installable via conda-forge. Using conda-forge for all of your packages can save you some serious headaches by avoiding dependency issues that can arise by mixing channels or installers.
Steps to Take Before Submitting to conda-forge

- Write unit tests (I like to use [pytest](https://docs.pytest.org/en/stable/))
- Ensure all dependencies are published on conda-forge already
- Write at least basic documentation for your package

It is ideal that you have written some unit tests for your package, so that they can be run when updating your conda-forge feedstock. You also should have your code documented so users have some idea of how to use it.
Adding Your conda-forge Recipe

- Fork [conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes)
- Create a new branch from the staged-recipes master branch
- Add a new recipe (meta.yaml) in the “recipes/<mypackagename>/ directory
- Submit these changes as a pull request (This will trigger testing on all operating systems)
- Once merged, your will get a new feedstock repository where your package will be built and uploaded to conda-forge!

Out of all of these steps, the only part that can be a bit confusing is creating your recipe. The file hierarchy you should create in the forked “staged-recipes” repo looks like this:
```
/recipes
    /<packagename>
        meta.yaml 
```
Below is the recipe I have used for one of my libraries, SWEpy. The recipe is a meta.yaml file much like the one used for your basic conda package with a little more detail required.

```{% set name = "swepy" %}
{% set version = "1.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a0462e693c4ed689be2e9050c1c7a932a5b015817d0ba6709a0231f090bc9b02

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - matplotlib-base
    - python >=3.6
    - pytest
    - pandas
    - requests
    - tqdm
    - pynco
    - gdal
    - scipy
    - affine
    - netcdf4
    - fsspec
    - xarray
    - mapboxgl
    - jenkspy
    - zarr

test:
  requires:
    - pytest
  files:
    - MEASURES/NSIDC-0630.001/2010.01.01/NSIDC-0630-EASE2_N3.125km-F17_SSMIS-2010001-37H-M-SIR-CSU-v1.3.nc
    - MEASURES/NSIDC-0630.001/2010.01.01/NSIDC-0630-EASE2_N6.25km-F17_SSMIS-2010001-19H-M-SIR-CSU-v1.3.nc
    - mock_server.py
  imports:
    - swepy
    - swepy.pipeline
    - swepy.nsidcDownloader
    - swepy.process
    - swepy.analysis


about:
  home: http://github.com/wino6687/swepy
  license: MIT
  license_family: MIT

  license_file: LICENSE
  summary: 'A python package for obtaining and manipulating Tb files from the MEaSUREs database'

  description: |
    SWEpy is a Python library designed to simplify access to a passive microwave brightness 
    temperature dataset available at the National Snow and Ice Data Center (NSIDC). 
    This dataset contains Northern and Southern hemisphere imagery along with Equatorial 
    imagery, and can be quite useful in analyzing snow water equivalent (SWE) over large spatial 
    extents. SWEpy contains tools to web scrape, geographically subset, and concatenate files into 
    time cubes. There is an automated workflow to scrape long time series while periodically stopping 
    to geographically subset and concatenate files in order to reduce disk impact.
  dev_url: https://github.com/wino6687/SWEpy

extra:
  recipe-maintainers:
    - wino6687
```

### There are a couple things to note:

- I am using my PyPI package as the source. This way, when I update my PyPI package with my CI service, my conda-forge package is automatically updated as well.
- I have a more complex testing suite setup for conda-forge that involves mocking a server and serving two small files in order to test file scraping without needing access to the web.
- Recipes can be much more complex than this, and involve installing dependencies outside of Python. Refer to the [conda-forge docs](https://conda-forge.org/docs/maintainer/adding_pkgs.html#the-recipe-meta-yaml) to see how to make more complex recipes.

Once you submit your pull request, someone from conda-forge will comment if there are any changes that need to be made before it is merged into it’s own feedstock. After it has been merged into its own feedstock, it will be built and then deployed so that it can be downloaded via the conda-forge channel!

## Wrapping Up

You now know how to publish your Python library on conda and conda-forge! But there is nothing more annoying than manually maintaining your packages in multiple places.

I solved this issue by setting up continuous integration with Travis-CI that automatically deploys any new versions of my code to PyPI, and then deploys new versions from PyPI to my conda-forge feedstock. **[Max: we use github actions instead]**

You can [read my other post](https://levelup.gitconnected.com/tools-for-writing-effective-and-robust-python-libraries-28bfd4c018c1) about how I setup my workflow to make Python libraries more robust. Continuous integration is your best friend when it comes to updating your libraries; Travis will run your unit tests, and if they pass, deploy them to keep your packages up to date. This way you never have to bother with manually uploading new versions again.

**Comment by mnm-matin** [comment]
Thanks @pz-max for putting the package on conda, was definitely an uphill task.
