### ISSUE TITLE
Want to extract features other than power? Write your requests in this issue ⬇️

### ISSUE THREAD

**Issue by mnm-matin** [pypsa-meets-earth/earth-osm#26]
Earth-OSM is currently only limited to Power infrastructure features. This is done on purpose, to get a stable v0 release.
This will remain so until v1 which is scheduled around February 2023. If you require any other features please list them in the comments. cheers!

**Comment by pz-max** [comment]
@Hazem-IEG feel free to correct.
Here a few map features that would be interesting to create LINKS or to distribute the demand:
- Key: aeroway, Value: aerodrome
- Pipeline e.g. gas pipeline: https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dpipeline
- Harbour: https://wiki.openstreetmap.org/wiki/Harbour

**Comment by davide-f** [comment]
Buildings: all

**Comment by mnm-matin** [comment]
Building is implemented, with the given features albeit,
the 'all' wildcard is still wip.

**Comment by mnm-matin** [comment]
all features are supported, so closing this
