### ISSUE TITLE
Some countries may be missing

### ISSUE THREAD

**Issue by davide-f** [pypsa-meets-earth/earth-osm#29]
Found a nice little bug? Fill out the section below. ⬇️

**Describe the bug**

In geofabrik, as known, some countries are merged into a non conventional code.
Some, such as Senegal and Gambia are already included, but some ar missing.
An example is malaysia, singapore and brunei. Only malaysia can be found.
This list may not be exhaustive.

With the previous implementation of PyPSA-Earth, we cleaned the [config_osm_data](https://github.com/pypsa-meets-earth/pypsa-earth/blob/main/scripts/config_osm_data.py) and verified for Asia, Africa and South America.
That may be of help hopefully.

I saw that the json is loaded from the website, but there are issues.
For example, saudi arabia, that is merged together with GCC is missing; some manual fixing may be needed, I will be doing that locally

**Comment by mnm-matin** [comment]
gcc can be extracted using 
either the country code: QA-AE-OM-BH-KW
or name gcc-states
see earth_osm view regions

the joint malaysia, singapore & brunei can be extracted using 
malaysia-singapore-brunei
or MY

verified as working using 
```bash
earth_osm extract power --regions gcc-states MY
```

let me know if it works for you

**Comment by davide-f** [comment]
> gcc can be extracted using either the country code: QA-AE-OM-BH-KW or name gcc-states see earth_osm view regions
> 
> the joint malaysia, singapore & brunei can be extracted using malaysia-singapore-brunei or MY
> 
> verified as working using
> 
> ```shell
> earth_osm extract power --regions gcc-states MY
> ```
> 
> let me know if it works for you

MY works but saudi arabia does not; the same applies for various countries in the pacific unfortunately.
if you search for "SA" in the json by geofabrik it is missing; "SA" is included in the gcc countries but it is missing unfortunately

**Comment by mnm-matin** [comment]
Hi Davide,
The geofabrik sitemap json is not meant as a replacement for an exhaustive list of all the countries in the world. It is a lists of all the pbf files available to download. If I check the geofabrik website for [asia](https://download.geofabrik.de/asia.html) and place my cursor over gcc-states, it highlights the region including saudi arabia. According to wikipedia the GCC includes Bahrain, Kuwait, Oman, Qatar, **Saudi Arabia**, and the United Arab Emirates. 

<img width="443" alt="lines extracted using earth osm" src="https://user-images.githubusercontent.com/45293386/215611962-67c9cb0d-4d49-432e-b18e-2d76321b2b40.png">
 
^created using
```bash
earth-osm extract power --regions gcc-states
```

**Comment by davide-f** [comment]
Yep, understanding that, just saying that there are problems with the location of 2 country letter codes so they is unreliable.
The workaround may is to use the other tag names.

**Comment by davide-f** [comment]
Closing
