### ISSUE TITLE
Host mkdocs documentation on readthedocs

### ISSUE THREAD

**Issue by pz-max** [pypsa-meets-earth/earth-osm#3]
I like that the documentation is in markdown. Atm the documentation is not deployed yet. We could host that on readthedocs for free as described here: https://www.mkdocs.org/user-guide/deploying-your-docs/

Further, we could
- Move contributing notes to the documentation
- Add a "Getting Started" chapter which includes e.g. the installation process, the tutorial (with results exploration example -> people don't know how to investigate the files. Maybe an explanation e.g. like VScode add-on can help). The [snakemake](https://snakemake.readthedocs.io/en/stable/index.html) documentation might help as orientation.

**Comment by mnm-matin** [comment]
closing
