### ISSUE TITLE
Bug in eo.py

### ISSUE THREAD

**Issue by Wuhochi** [pypsa-meets-earth/earth-osm#31]
dear developer, hi

i find maybe there is a bug. when i runcode, find error in eo.py
'IndentationError: expected an indented block after 'if' statement on line 53'

I originally intalled the earth-osm by pypsa-earth, and the earth-osm version is 0.0.9

**Comment by mnm-matin** [comment]
Thanks for reporting the bug. I think there was some mixup with the pip or conda production branches. Which one did you use to install the package? Maybe a direct install from the git repo is the safest option right now. @pz-max can you please make sure the conda package matches the pip version.

**Comment by Wuhochi** [comment]
> Thanks for reporting the bug. The bug has been reported to be fixed in earth-osm 0.1.0, please try to upgrade your package version. I think there was some mixup with the pip or conda production branches. Which one did you use to install the package? Maybe a direct install from the git repo is the safest option right now. @pz-max can you please make sure the conda package matches the pip version.

thanks for your kind reply, I think my earth-osm should be downloaded by conda-forge (as part of pypsa-earth's install)

**Comment by pz-max** [comment]
@mnm-matin this is done already. Every new conda installation should work smooth
