### ISSUE TITLE
Some regions (e.g. Panama) do have the id but not the country code and cannot be accessed with the country code

### ISSUE THREAD

**Issue by davide-f** [pypsa-meets-earth/earth-osm#33]
When running `earth_osm view regions`, "panama" is available in central-america with flag "panama" but NaN country code.
When using earth_osm using PA, it does not work. When country_code is NaN, it may be filled using country_converter, that would help a lot.
I fear this may occur for other countries as well.

```
        {
            "type": "Feature",
            "properties": { 
                "id" : "panama",
                "parent" : "central-america",
                "name" : "Panama",
                "urls" : {
                    "pbf" : "https://download.geofabrik.de/central-america/panama-latest.osm.pbf",
                    "bz2" : "https://download.geofabrik.de/central-america/panama-latest.osm.bz2",
                    "shp" : "https://download.geofabrik.de/central-america/panama-latest-free.shp.zip",
                    "pbf-internal" : "https://osm-internal.download.geofabrik.de/central-america/panama-latest-internal.osm.pbf",
                    "history" : "https://osm-internal.download.geofabrik.de/central-america/panama-internal.osh.pbf",
                    "taginfo" : "https://taginfo.geofabrik.de/central-america/panama/",
                    "updates" : "https://download.geofabrik.de/central-america/panama-updates"
                }
            }
        },
```

**Comment by davide-f** [comment]
I investigated a bit the issue and a potential fix is in https://github.com/davide-f/earth-osm/tree/parse_nan_country_codes .
However, my feeling is that this postprocessing makes things more complicated.

I think this is a feature not desirable for the main repo: the conversion may convert too much.

**Comment by mnm-matin** [comment]
I believe you can use the name, country code or a mixture of them.

**Comment by davide-f** [comment]
Indeed, I've implemented that.
At the beginning it sounded weird but it is the most suitable approach.
Since you agree, I close this issue
