### ISSUE TITLE
Add Area as an element

### ISSUE THREAD

**Issue by mnm-matin** [pypsa-meets-earth/earth-osm#37]
I've been working on that commit for a while now, and have only picked it up again a few days ago. In particular the data pipeline needs to be modified so that it can handle: Node (Towers), Way (Lines and Cables), Area (Substations and Generators). There is some [detection](https://wiki.openstreetmap.org/wiki/Overpass_turbo/Polygon_Features) that needs to occur if something is a way or an area. [More info on ways from OSM](https://wiki.openstreetmap.org/wiki/Way). Ways are converted to LineStrings while Areas are converted to Polygons. Currently all Nodes are converted to Points which is wrong and would cause problems with buildings etc. [relevant code from osmnx here](https://github.com/gboeing/osmnx/blob/main/osmnx/geometries.py).

As a checklist:
- [ ] function way_or_area
- [ ] function way_to_linestring
- [ ] function area_to_polygon
- [ ] update the core data flow to use the new functions
- [ ] function polygon_to_point and add a --nodes-as-points flag to args
- [ ] update writing to csv
- [ ] update writing to gdf

_Originally posted by @mnm-matin in https://github.com/pypsa-meets-earth/earth-osm/issues/14#issuecomment-1516842069_

**Comment by mnm-matin** [comment]
The update config would look something like this:

```python
    "power": {
        "substation": ("node", "area"), 
        "generator": ("node", "way", "area"),
        "line": ("way"),
        "tower": ("node"),
        "cable": ("way"),
        }
```

**Comment by davide-f** [comment]
@mnm-matin Nice PR. Can this be closed now?
