### ISSUE TITLE
More tags in geojson file

### ISSUE THREAD

**Issue by zoobar** [pypsa-meets-earth/earth-osm#41]
The geojson file misses a lot of tags e.g. 'name'. It would be great to have more control over the tags that get written into geojson.

**Comment by mnm-matin** [comment]
Absolutely, the only problem is that there can be upwards of 300 tags for a feature, this creates very sparse geojson. One idea that is currently implemented is to move tags with x% of null values to a column called 'other_tags'. I have to think about how to solve this problem.

**Comment by mnm-matin** [comment]
in the current implementation if a tag has 95% missing values, it is moved to a column called other_tags. The idea is that if 95% of the values are missing then it is very unlikely to be useful for most purposes. The function tags_explode in earth_osm.utils allows one to bring back the original dataframe.
