### ISSUE TITLE
ValueError: Must have equal len keys and value when setting with an iterable

### ISSUE THREAD

**Issue by davide-f** [pypsa-meets-earth/earth-osm#47]
Found a nice little bug? Fill out the section below. ⬇️

**Describe the bug**
Value error, see https://github.com/pypsa-meets-earth/pypsa-earth/actions/runs/7306231974/job/19910723923
When running the pypsa-earth workflow in https://github.com/pypsa-meets-earth/pypsa-earth/actions/runs/7306231974/job/19910723923
the following error is triggered:
ValueError: Must have equal len keys and value when setting with an iterable

**To Reproduce**

Run pypsa-earth tutorial in https://github.com/pypsa-meets-earth/pypsa-earth/pull/943

**Expected behavior**

The workflow to run

**Comment by GbotemiB** [comment]
I faced the same issue. What I realized was that this only happens when the country or region is atleast 2. Whenever it brings up the error `ValueError: Must have equal len keys and value when setting with an iterable`, my workaround is to rerun the snakemake command.

But I think the issue is related to the data in the power folder. If the files are not complete yet, it will throw the error `ValueError: Must have equal len keys and value when setting with an iterable`.

**Comment by GbotemiB** [comment]
Hi @davide-f, the reason for the error seems to be coming from 
https://github.com/pypsa-meets-earth/earth-osm/blob/714ab0d9762d3715fdd1ebb1eba6af1773070004/earth_osm/utils.py#L234

There are two fixes for this. One of the fixes is to uncomment the following lines. I think @mnm-matin was working on this already
https://github.com/pypsa-meets-earth/earth-osm/blob/714ab0d9762d3715fdd1ebb1eba6af1773070004/earth_osm/utils.py#L195-L205

The other fix is to implement a `continue` statement into the loop 
https://github.com/pypsa-meets-earth/earth-osm/blob/714ab0d9762d3715fdd1ebb1eba6af1773070004/earth_osm/utils.py#L228-L234

```bash
for col, val in other_tags.items():
            # if val is a list, convert it to a string
            if isinstance(val, list):
                val = str(val)

            # Check if the column exists in the DataFrame
            if col not in df_melt.columns:
                logger.warning(f"Column '{col}' not found in dataframe.")
                continue

            # Set the value in the DataFrame
            df_melt.at[index, col] = val
    ```

These are my proposed fixes.

**Comment by davide-f** [comment]
@mnm-matin what do you think?

**Comment by mnm-matin** [comment]
now solved
