### ISSUE TITLE
Add option of country code ISO standard

### ISSUE THREAD

**Issue by pz-max** [pypsa-meets-earth/earth-osm#5]
We discussed recently in a PyPSA-Earth workflow meeting that considering the package has global scope, using a 2 letter ISO code is probably not the best. Just imagine you extract data for 100 countries. The 2-letter codes become really quickly quite challenging to distinguish...

I think to provide maximal flexibility, we should over an option to include 2-letter (ISO), 3-letter (ISO), or full country (NOT ISO) naming options. The user can pass only one of the options or all of them.

**Comment by pz-max** [comment]
3-letter code converter probably needs to be added [gfk_data.py](https://github.com/pypsa-meets-earth/earth-osm/blob/fcfb5896b67224050bd173c3246e57edb2c7ac07/earth_osm/gfk_data.py#L118-L130) somewhere or in the `utils.py`

- The function could be smt like `get_code3_by_code` (we have a function in pypsa-earth which is doing that [here](https://github.com/pypsa-meets-earth/pypsa-earth/blob/0713b1427a3eb9c8457b50d36a36ce343e210ca5/scripts/_helpers.py#L488-L508))

I am not sure yet where the 2letter/3letter/country name options should be passed, needs some more time..

**Comment by mnm-matin** [comment]
iso3166-1:alpha2 or iso3166-2 are supported in addition to full names. They can be mixed as well. The following works:
`
earth_osm extract power --regions DE benin US-TX 
`
You're right It could be better documented (see Advanced Usage section in the README)

I'm going to leave three-letter to two letter conversion up to the user as its quite easy to do (or at most document how to do it)

**Comment by pz-max** [comment]
Let's maybe rename this issue: 'Allow user to input and output 3-letter iso-code' ?

In PyPSA-Earth we would prefer passing e.g. 3-letter codes, PyPSA-EUR prefers passing 2-letter codes. Allowing both would be great. Regarding the output, having an option if the output contains 2/3- letter iso code would be great.

No need to implement it now, but just let us track that so some can take care of it in future @mnm-matin
