### ISSUE TITLE
eo.save_osm_data() always creates csv files (even if not selected)

### ISSUE THREAD

**Issue by bobbyxng** [pypsa-meets-earth/earth-osm#50]
**Describe the bug**
eo.save_osm_data() always creates .csv (default) output even if only "geojson" is selected/needed. This creates overhead, especially if only one particular file type is needed.

**To Reproduce**
Run: 

```

from earth_osm import eo

import earth_osm as eo

eo.save_osm_data(
  primary_name = 'power',
  region_list = ['benin', 'monaco'],
  feature_list = ['substation', 'line'],
  update = False,
  mp = True,
  data_dir = './earth_data',
  out_format = [ 'geojson'],
  out_aggregate = False,
)

```

**Expected behavior**
Only output .geojson files

**Desktop (please complete the following information):**
 - OS: Linux/Ubuntu
 - Version: 22.04 LTS

**Comment by mnm-matin** [comment]
fixed in [8753033](https://github.com/pypsa-meets-earth/earth-osm/commit/8753033b4d4e6d27a888aa2e8daefd12bf9e89fe)
