### ISSUE TITLE
Allow to disable progress bar

### ISSUE THREAD

**Issue by FabianHofmann** [pypsa-meets-earth/earth-osm#52]
Thank you for the nice package, it is working like charm :) 

In many CI's the `tqdm` progress bar is printed out over many lines. This is the same for the pypsa-earth CI where the retrieval from earth-osm is printing out several hundred lines (see https://github.com/pypsa-meets-earth/pypsa-earth-sec/actions/runs/10320381005/job/28570828550#step:8:199). 

I would be wonderful and very helpful to let the user decide whether to use the `tqdm` or not.   

As far as I see the only change required would be a argument in the `download_file` function. If the maintainers agree, I would propose a pr.

**Comment by mnm-matin** [comment]
merged #53 , many thanks @FabianHofmann !
