### ISSUE TITLE
Implement or test download accelerators

### ISSUE THREAD

**Issue by pz-max** [pypsa-meets-earth/earth-osm#7]
Just saw a comment about [download accerlators](https://stackoverflow.com/questions/93642/how-do-download-accelerators-work). I think raising this as an enhancement/feature request will help track this performance opportunity. Checking out the commented package [pySmartDL](https://github.com/iTaybb/pySmartDL), it looks the package is not too active anymore -- maybe there are new alternatives?

The pySmartDL package and the author also refer to a couple of HTTP websites (not HTTPS). Why HTTP is no not secure is written in this [article](https://www.cloudflare.com/en-gb/learning/ssl/why-is-http-not-secure/). This can be dangerous and opens the user to a number of attacks:
- [On-path attacks](https://www.cloudflare.com/learning/security/threats/on-path-attack/)
- [DNS hijacking](https://www.cloudflare.com/learning/dns/dns-security/)
- [BGP hijacking](https://www.cloudflare.com/learning/security/glossary/bgp-hijacking/)
- [Domain spoofing](https://www.cloudflare.com/learning/ssl/what-is-domain-spoofing/)

Anyways, the concept and application of download accelerators can enhance the package. Would be an awesome feature.

**Comment by mnm-matin** [comment]
download accelerators can be damaging to server infrastructure, especially free hosting sites like geofabrik. This will not be implemented. There are ideas to host filtered primary features in future versions.
